### ISSUE TITLE
Did you try without the the sigmoid and tanh layer at the end

### ISSUE THREAD

**Issue by adhara123007** [roatienza/densemapnet#2]
Hi Sir,

I went through the paper and the code. I feel the sigmoid layer and the tanh layer at the end is very misleading. It compresses the entire range of the output and thus improves convergence.
Have you tried without the sigmoid and the tanh layer at the end?
Does the network converge?

Thanks and Regards,
Arnab

**Comment by roatienza** [comment]
The code was tested on sigmoid output. I tried tanh but got a lower performance.
