### ISSUE TITLE
How to modify the model to fit image pairs of arbitrary position?

### ISSUE THREAD

**Issue by lawsonsli** [roatienza/densemapnet#4]
If the image pairs don't have horizontal epilines, but we have left camera and right camera poses.
In this case, how to modify this network？
Thanks.

**Comment by roatienza** [comment]
The network is epipolar line agnostic. So, as long as you train it on consistent data samples (fr left and right cameras with consistent epipolar line or fixed stereo config), the network regresses the ground truth labels (depth).
